### PR TITLE
Add foreman action template

### PR DESCRIPTION
**Pull request by dosas**
https://github.com/theforeman/actions/blob/v0/.github/workflows/test-gem.yml

### CODE REVIEW

**Comment by dosas** [comment]
@nadjaheitmann looks like ruby 2.5 is missing --strict parameter
```
Run if compgen -G "*.gemspec" > /dev/null ; then
  if compgen -G "*.gemspec" > /dev/null ; then
    gem build --verbose --strict *.gemspec
  fi
  shell: /usr/bin/bash -e {0}
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --strict
Error: Process completed with exit code 1.
```

Do we still need support for this version or can we drop it?

**Comment by nadjaheitmann** [comment]
I suppose that we can drop it.

**Comment by nadjaheitmann** [comment]
Well, as there are actually no unit tests for this plugin, we should probably also disable the test. It gives a false impression...

**Comment by dosas** [comment]
Maybe the wording is misleading. I changed it to verify. This job actually found some problems with different ruby versions so I would advise against dropping it.

https://github.com/ATIX-AG/hammer-cli-foreman-scc-manager/actions/runs/7988133927/job/21812083400
https://github.com/ATIX-AG/hammer-cli-foreman-scc-manager/actions/runs/7989378825/job/21815849267

**Comment by nadjaheitmann** [comment]
But the recent run was successful as I can see?

**Comment by dosas** [comment]
yes

**Review by nadjaheitmann — APPROVED** [review]

**Pull request merged**
